# Site settings
title: SpeedTracker
description: Website performance monitoring tool
baseurl: ""
url: "https://speedtracker.org"

# Build settings
markdown: kramdown

toolkitUrl: "https://speedtracker-toolkit-wunjwvrnzb.now.sh"

detach:  false
port:    4830
host:    0.0.0.0
